version: '3.9'

services:
  server:
    image: hanhongyong/ms365-e5-renew-x:latest
    container_name: renewx
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    privileged: true
    volumes:
      - ./app/Deploy:/app/Deploy
      - ./app/appdata:/app/appdata
      - /etc/localtime:/etc/localtime
    ports:
      - "9060:1066"