version: '3'

networks:
  hellohao:
    external: false
    
services:
  # hellohao容器运行部分，第一次运行可将此部分注释
  
  hellohao:
    image: maven:3.3-jdk-8
    container_name: hellohao
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    privileged: true
    networks:
      - hellohao
    volumes:
      - ./app/Tbed.jar:/Tbed.jar
      - ./app/application.properties:/application.properties
      - ./data/HellohaoData:/HellohaoData/tbedlog
      - ./data/upload_tmp:/data/upload_tmp
      - /etc/localtime:/etc/localtime
    ports:
      - "8088:8088"
    command: [
        'java',
        '-jar',
        'Tbed.jar'
        ]

  # hellohao容器运行部分，第一次运行可将此部分注释

  mysqlserver:
    image: mysql:5.7.22
    restart: always
    container_name: mysqlserver
    networks:
      - hellohao
    ports:
      - 9306:3306
    privileged: true
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: picturebed
      MYSQL_USER: hellohao
      MYSQL_PASSWORD: hellohao
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf


    # phpmyadmin数据库管理部分，正式运行时可注释此段代码以关闭phpmyadmin运行

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    networks:
      - hellohao
    restart: always
    ports:
      - 9180:80
    environment:
      - PMA_ARBITRARY=1

    # phpmyadmin数据库管理部分 