version: '3.9'

services:
  server:
    image: rabbitmq
    container_name: rabbitmq
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    restart: always
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "8080:15672"

