version: '3'

services:
  server:
    image: sscms/core:latest
    container_name:  sscms
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSCMS_SECURITY_KEY=e2a3d303-ac9b-41ff-9154-930710af0845
      - SSCMS_DATABASE_TYPE=SQLite
    restart: always
    privileged: true
    volumes:
      - ./sscms:/app/wwwroot 
      - /etc/localtime:/etc/localtime
    ports:
      - "9080:80"

