version: '3.9'

services:

  waline:
    container_name: waline
    image: lizheming/waline:latest
    restart: always
    ports:
      - "8360:8360"
    volumes:
      - ./data:/app/data
    environment:
      TZ: 'Asia/Shanghai'
      MONGO_HOST: 'mongo'
      MONGO_PORT: '27017'
      MONGO_DB: 'waline'
      MONGO_USER: 'dev'
      MONGO_PASSWORD: 'example'
      SITE_NAME: 'Your site name'
      SITE_URL: ''

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./app/mongo:/etc/mongo
      - ./app/datadir:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testtest