version: '3'

services:
  server:
    image:
    container_name: 
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "9080:80"

