version: '3.9'
  
services:
  server:
    image: ipfs/kubo
    container_name: kubo
    environment:
      - USER_UID=1000
      - USER_GID=1000
      # - PRIVATE_PEER_IP_ADDR=..
      # - PRIVATE_PEER_ID=...
    restart: always
    volumes:
      - ./app/ipfs_data:/data/ipfs
      # - ./001-test.sh:/container-init.d/001-test.sh
    ports:
      - "4001:4001"    
      - "8080:8080"
      - "5001:5001"


